### PR TITLE
Exchange update

### PR DESCRIPTION
**Pull request by sandakersmann**
Remove Bitspark, ExchangeMyCoins and Melotic

### CODE REVIEW

**Comment by sandakersmann** [comment]
@TheWildHorse Please merge :)

**Comment by sandakersmann** [comment]
@FuzzyBearBTC Please merge :)

**Comment by FuzzyBearBTC** [comment]
Any reason why these exchanges have dropped PPC?? no trade volumes? or were they never offering ppc trades?

**Comment by sandakersmann** [comment]
@FuzzyBearBTC https://bitcoinmagazine.com/20330/bitspark-closes-exchange-focus-establishing-bitcoin-remittance-service/

**Pull request merged**
