### PR TITLE
Update of tickerinfo

### PR DESCRIPTION
**Pull request by sandakersmann**
The tickerinfo has been running on the backup solution for over a year. This is my attemt on fixing this. I don't have much skills in PHP, so someone should do a major review before we merge this.

### CODE REVIEW

**Comment by sandakersmann** [comment]
@TheWildHorse Can you do a review on this?

**Comment by FuzzyBearBTC** [comment]
looks good to me :+1:

**Comment by TheWildHorse** [comment]
@sandakersmann I'm pretty sure I already seen this pull, where is the "file_get_api" method defined? I don't see it's definition nowhere, and you can't use it if it doesn't exist. Correct me if I'm wrong.

**Comment by sandakersmann** [comment]
@TheWildHorse After some research I am pretty sure you are correct. Thank you for your review. Made a new pull with the changes. Ref: #230

**Pull request closed without merging**
