### PR TITLE
Urgent update of download-peerunity page 26.03.16

### PR DESCRIPTION
**Pull request by sandakersmann**
Updated links to Peerunity 0.2.0

### CODE REVIEW

**Comment by sandakersmann** [comment]
@TheWildHorse @FuzzyBearBTC Please merge ASAP :)

**Comment by sandakersmann** [comment]
@TheWildHorse @FuzzyBearBTC Bump

**Comment by sandakersmann** [comment]
@super3 @brossi Please merge :)

**Comment by sandakersmann** [comment]
Bump

**Comment by sandakersmann** [comment]
@sunnyking @glv2 @sigmike Do you guys have merge access?

**Comment by TheWildHorse** [comment]
Sorry for the late response. Merged.

**Comment by sandakersmann** [comment]
No worries :)

**Pull request merged**
