### PR TITLE
Update en.php

### PR DESCRIPTION
**Pull request by MAL315**
I added some recommendations or changes specifically on the homepage which I think would appeal more to the general public and less to hardcore cryptocoin enthusiasts. Enthusiasts already know about us but we want the masses to start investing in Peercoin right? I didn't focus too much on how Peercoin should be positioned but eventually I see it more as Primecoin or Bitcoin being used for transactions and Peercoin being used as a savings account. That's a new branding entirely so should probably go through more discussion.

- index.why_peercoin_desc: I think specifying the 1% early on is important since that's such a big reason as to why I mined and bought Peercoins to begin with. I found it was too far down the page (only under Investors). 

- index.transparent_protocol_desc: Changed it from Transparent Protocol to Secure Protocol, "Strong and reliable 4 years and counting". The masses might not care so much about it being open source. Although I love open source and think it's important I didn't think it needed to be in the first 4 points. Highlighting that it's been secure for 4 years will show everyone that we're not new to this and our network is still going strong even though other networks might be struggling. With the flood or crypto coins I think it's important to state the 4 years which is something other coins can't state themselves.

- index.investors_desc: Guaranteed 1% return. Again for general masses, do they need to fully understand minting in this description? To me just knowing I get 1% back regardless of how it works is good enough.

- investors.guaranteed_returns_desc: related to the point about, learn more about how to mint could be listed here instead. I think we need to state that the coins can also be purchased from an exchange (not only from mining). I had issues with this initially when I came back to buy coins (I had mined previously so wasn't a newcomer or beginner, clicked investor but saw no reference to the exchange).

### CODE REVIEW

**Comment by FuzzyBearBTC** [comment]
We need to sort out the updated translations for these changes to, happy to merge otherwise good work @MAL315 +1:

**Comment by FuzzyBearBTC** [comment]
Yup that is the process as I remember, I just wanted to make a note of it here so Transifex is also updated

**Comment by MAL315** [comment]
Site isn't loading for me.. not sure why?

**Comment by MAL315** [comment]
I don't see any more majors changes so I'm guessing it has to do with uploading from Github to the webserver?

**Comment by FuzzyBearBTC** [comment]
https://github.com/super3/peercoin.net/pull/267/commits/36e1b9a567defb863880c87b27e18143d0af64e2 is the commit i am wondering might have caused an issue?

**Comment by MAL315** [comment]
#267 wasn't approved though, only the en.php file and the 2 translation 
files.

**Comment by MAL315** [comment]
and this one is just an image file, I can't see how that would erase everything. If I do view source on peercoin.net there's basically nothing..

**Comment by MAL315** [comment]
Maybe you can try approving the copyright 2015/2016 commit just to see if it forces a re-upload of everything?

**Comment by FuzzyBearBTC** [comment]
yup same on view source code.. this usually happens from a malformatted php file though, sry yes you are right on that commit not being accepted yet i thought I had and was the only one i was unsure about but hence I did not merge till the others were done and site working.

**Comment by FuzzyBearBTC** [comment]
just merged the copyright 2015/2016 commit, so lets see what happens

**Comment by MAL315** [comment]
I'm not exactly sure how the web server gets its info from Github, do you have access to everything or does that portion rely on Super3?

**Comment by FuzzyBearBTC** [comment]
nope unfortunately that was all setup by @super3 and I do not have access to the server to have a look. Might be worth putting one single pull request in to revert all changes just to be double sure it not an error introduced by the changes though agreed looking over them I can not see anything obvious.

**Comment by MAL315** [comment]
I downloaded the site locally and when I run index.php it does launch with more content than what's seen on peercoin.net, I'm thinking it's really more of an issue with the transfer from Github to Super3's web server. They were all really simple text changes and even pages that weren't modified are blanked out on the web server.

**Comment by MAL315** [comment]
I sent a new commit with a file from history, give it a shot.. I can 
redo the other 2 also. It's not possible to undo a commit once it's 
submitted?

**Pull request merged**
