### PR TITLE
Fix markup of leaflist so the bullets stay on the same line as the text

### PR DESCRIPTION
**Pull request by nauadratti**
Currently it is broken in many languages with long words.

### CODE REVIEW

**Comment by MAL315** [comment]
Thanks for fixing this, I had noticed it on some of the translated pages. Could you resubmit it on https://github.com/peercoin/peercoin.net? We've recently changed the repo for peercoin.net to this new one.

**Comment by nauadratti** [comment]
Done. Would you accept the PR here too?

**Comment by nauadratti** [comment]
@MAL315 Could you merge this one too?

**Comment by MAL315** [comment]
Sure, but this repo isn't used anymore (we moved over to the other one on Tuesday). We're just working on a few remaining things before we shut it down.

**Pull request merged**
