### PR TITLE
Exchange update

### PR DESCRIPTION
**Pull request by sandakersmann**
Added Melotic and removed ANXPRO and Vault of Satoshi

### CODE REVIEW

**Comment by sandakersmann** [comment]
@TheWildHorse Please merge :)

**Comment by sandakersmann** [comment]
@TheWildHorse Also removed Crypto-Trade. Please merge :)

**Comment by sandakersmann** [comment]
@TheWildHorse Also added PS Coin to exchanges. Please merge :)

**Comment by sandakersmann** [comment]
@FuzzyBearBTC Can you merge this pull, please.

**Comment by TheWildHorse** [comment]
Sorreh, mergeing now.

**Pull request merged**
